### ISSUE TITLE
Dev mode support

### ISSUE THREAD

**Issue by PilchardFriendly** [jgable/connect-assets-jspaths#1]
Great work on this - it's just what I was looking for to reduce changes in markup as our client-side javascript changed.

Any suggestions on how to pick-up changes to javascript on the fly?  At the moment, all the assets are 'assetised' on startup, which slows down our dev flow.  

 I notice that connect-assets will do this, and it has it's own compiler path.  I see that one has to prime the cache first though, by explicitly mentioning which resource are necessary.  

Perhaps calling 'js' with the output of the files detected on disk would be a good start?

What do you think?

**Comment by jgable** [comment]
Thanks for the feedback.  I think that would be a nice feature to have.  

Unfortunately, the reason that connect-assets can keep real time versions of the files is because they are probably being referenced in the views and at each request they are rebuilt.  When you are using something like require js, the scripts aren't referenced in the views like normal and so they aren't rebuilt with every request.

We could just call the `jsPaths assets` on every request, but that would probably get old pretty quick.

In an ideal world, here is how I think this should work:
- If not in production mode
- We would run a file monitor for the connect assets js root that detects file changes
- When a file is changed, we would call the connect assets js function on it
  - If there is an error, output it to the logs, but keep the original compiled file?
  - If successful, replace the original compile file and the next request will serve the latest file

Some down sides to this would be increased battery drain because of the file watching, but we could always provide a config option to disable the real time updates.

I'll try to find some time to look into this this week.

**Comment by jgable** [comment]
Got tied up in some other things, but still hoping to get to this by next week.

**Comment by PilchardFriendly** [comment]
Jacob

No worries.  I switched to just walking the tree at startup.  No need to do it every view.  This solution needs something more probably to work with the optimiser, but I can live with that for now.  

Cheers, 
Nick

**Comment by jgable** [comment]
I've added this to the current package and re-published.  Here are some directions from the Readme about how to use:

### Watch changes and re-compile

Now you can pass some additional callbacks in and it will monitor your connect assets directories for changes.

```
fileChangedCallback = (err, filePath) ->
    console.log "File Changed: #{filePath}"

jsPaths assets, console.log, fileChangedCallback, (err, watcher) ->
    console.log "Watcher initialized"
```

Just pass a fileChangedCallback (can be null) and a done callback for when the watcher is loaded.  Files are automatically assetized whenever a change is detected.
